services:
  postgres:
    image: postgres:18
    container_name: postgres18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=1234
    # ports:
    #   - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # pg_admin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=contact@lmello.dev
  #     - PGADMIN_DEFAULT_PASSWORD=1234
  #   ports:
  #     - "5433:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   healthcheck:
  #     test: [ "CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1/misc/ping')\"" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s

  status_page_backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: status_page_backend
    restart: unless-stopped
    environment:
      - DATABASE_CONFIG__USER=status_page_user
      - DATABASE_CONFIG__PASSWORD=1234
      - DATABASE_CONFIG__HOST=postgres
      - DATABASE_CONFIG__PORT=5432
      - DATABASE_CONFIG__DATABASE=status_page
      - DATABASE_CONFIG__ECHO=false
      - LOGGING_CONFIG__JSON_FORMAT=true
      - LOGGING_CONFIG__LIBRARY_LOG_LEVELS={"httpx":"WARNING", "apscheduler.scheduler":"WARNING"}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/py-status-page/stats/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s

  status_page_angular:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: status_page_frontend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      status_page_backend:
        condition: service_healthy
    ports:
      - "4200:80"

volumes:
  postgres_data:
  pgadmin_data:
